### PR TITLE
fix: updated text on resource section to make it service indipendant

### PR DESCRIPTION
**Pull request by acarranoqovery**
# What does this PR do?
Update the text on the resource section to make it more generic and avoid customization by service type

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ ] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by acarranoqovery** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix: updated text on resource section to make it service indipendant - 2023-04-13T15:19:34Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/46737dc3-e12b-42a2-b0bf-272f7a67f18c/services/general)

 Another comment will be posted when deployments are terminated

**Comment by acarranoqovery** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z46737dc3-z81333e90-gtw.zc531a994.rustrocks.cloud)

**Review by RemiBonnet — COMMENTED** [review]
Thanks @acarranoqovery, could you remove the `package-lock.json` of this PR?

**Comment by acarranoqovery** [comment]
> Thanks @acarranoqovery, could you remove the `package-lock.json` of this PR?

done!

**Review by RemiBonnet — APPROVED** [review]

**Pull request merged**
