### PR TITLE
feat(cluster-settings): features section

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-499)

- Add settings section for Cluster
Capture d’écran 2023-01-30 à 18 32 04

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(cluster-settings): features section - 2023-01-30T17:32:21Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/4e79e3ae-82db-40d8-b200-39e0e66e8d26/services/general)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z4e79e3ae-z48dce920-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z4e79e3ae-z6895acdc-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
At first I thought you made a mistake with your title `page-settings-features-feature`... then I realised... 
Good job, worked pretty well!

**Pull request merged**
