### PR TITLE
feat(services): rewrite service list with Helm support

### PR DESCRIPTION
**Pull request by ctjhoa**
# What does this PR do?

https://qovery.atlassian.net/browse/FRT-873
https://qovery.atlassian.net/browse/FRT-613

### CODE REVIEW

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery  preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery  preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> There are two hard problems in computer science: naming things, cache invalidation and off-by-1 errors

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] staging - Frt 873 react query on service list first raw helm implementation - 2023-11-10T08:36:09Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/c78b0f4a-29f0-4e9b-a7d9-66372d1cc2d4/services/general)

 Another comment will be posted when deployments are terminated

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://956-console-staging.zc531a994.rustrocks.cloud)

**Review by RemiBonnet — CHANGES_REQUESTED** [review]
Thanks @ctjhoa !!

- I tested the filters, and the column resize when we use it, I think it should be fixed (same when we come from skeleton to table with datas)
- And, when we click to copy the commit id we have little jump

You can see a record here : https://www.loom.com/share/923bcf89c7cc4b9ca864682cf33982ec

**Review by RemiBonnet — APPROVED** [review]

**Pull request merged**
