### PR TITLE
fix(error): add info in database error messages

### PR DESCRIPTION
**Pull request by bdebon**
# What does this PR do?

[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-564)

The error message was empty, now it displays what we know.

CleanShot 2022-11-23 at 11 51 02@2x

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix(error): add info in database error messages - 2022-11-23T10:51:43Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/43265535-aea4-4496-99ef-2347ead434bd/applications)

 Another comment will be posted when deployments are terminated

**Comment by bdebon** [comment]
I also found a better way to print the message without typing the error with any

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z43265535-z4256f03b-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z43265535-z09a507b0-gtw.za8ad0659.bool.sh)

**Review by RemiBonnet — APPROVED** [review]

**Pull request merged**
