### PR TITLE
Chore/updating text

### PR DESCRIPTION
**Pull request by alecarrano**
# What does this PR do?
Changing text based on Pierre's feedback
> Link to the JIRA ticket

Put description here

> Screenshot of the feature

Put screenshot following the template `before` => `after` here

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [ ] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [ ] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - Chore/updating text - 2022-10-04T07:43:45Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/1cd0e056-b9dc-4477-9e8d-b4c09fb965c8/applications)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z1cd0e056-zd24419c9-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z1cd0e056-z421c6713-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
Excellent PR @alecarrano 20/20.

**Pull request merged**
