### PR TITLE
Fix circular dependencies for shared/utils

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

- Fix circular dependencies with the `utils` library
- Create library Router
- Create library Auth

---

### Global

- [x] This PR does not introduce any breaking change
- [x] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by RemiBonnet** [comment]
A preview environment was automatically created via Qovery.  
Click on the link below to follow its deployment and use it.  
:point_right: [[PR] staging - Fix circular dependencies for shared/utils - 2022-06-10T09:26:04Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/229ac625-667c-4bca-86a9-65e3031793ed/applications)

**Review by WilliamTraoreee — APPROVED** [review]
👍

**Pull request merged**
