### PR TITLE
Adding Qovery Open-api

### PR DESCRIPTION
**Pull request by RemiBonnet**
# Adding Qovery Open-api
Using the package _**qovery-typescript-axios**_
- Update all requests
- Update all interfaces
- Update all enums

### Global

- [ ] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labelled as such
- [ ] I have found someone to review this PR and pinged him

### Store 

- [ ] This PR introduces new store changes

### NX 

- [ ] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [ ] I made sure the code is type safe (no any)
- [ ] I have run the unit tests locally
- [ ] I have run the e2e tests locally
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by bdebon** [comment]
Hey @RemiBonnet I have finished refactoring everything and adding the last version of the auto-generated API. That works super nicely I am so so so happy! I let you review the branch and tell me if it's good for you.
I have ran the tests, there is no breaking changes.

**Comment by bdebon** [comment]
Soon to be released. I need to fix the tests and add one small one. Tomorrow will be the day!

**Comment by RemiBonnet** [comment]
@bdebon well done!

**Pull request merged**
