### PR TITLE
fix(console-shared): folder architecture

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

- Here is an example of how to structure components for the **console-shared** library  
- Cleaning for `git-repository-settings` and `buttons-actions` 

Capture d’écran 2022-12-23 à 11 22 59

Capture d’écran 2022-12-23 à 11 23 27

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix(console-shared): folder architecture - 2022-12-23T10:23:45Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/4fe88dd5-76c1-49ae-beb5-cf5df970b891/applications)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z4fe88dd5-z5cc66ede-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z4fe88dd5-zfe0336e7-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
Perfect Remi, super initiative. I'm gonna continue the renaming/refactoring on another PR

**Pull request merged**
