### PR TITLE
chore(ci): simplifying github actions

### PR DESCRIPTION
**Pull request by bdebon**
This pr clean the github actions that was a little bit too complex and out-to-date by using latest nx recommendations.
It makes a better usage of nx agents, parallelized more actions, making a better usage of nx cache, and restore colors in logs.
It's also a good prep work for coming image registry deployment if we want to implement it. 

Before
CleanShot 2022-10-31 at 15 38 18@2x

After
CleanShot 2022-10-31 at 15 38 58@2x

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - chore(ci): simplifying github actions - 2022-10-31T11:15:59Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/e8b3a41c-2181-4ffc-848a-e0ceb1b56926/applications)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://ze8b3a41c-z627b77bf-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://ze8b3a41c-z275baaf8-gtw.za8ad0659.bool.sh)

**Review by RemiBonnet — APPROVED** [review]
LGTM 👍

**Pull request merged**
