### PR TITLE
fix(ui): fix breadcrumb and link truncation

### PR DESCRIPTION
**Pull request by ctjhoa**
# What does this PR do?

https://qovery.atlassian.net/browse/FRT-1202

### CODE REVIEW

**Comment by RemiBonnet** [comment]
[Qovery Preview](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Make it work, make it right, make it fast

**Comment by RemiBonnet** [comment]
[Qovery Preview](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] my-env - fix(ui): fix breadcrumb and link truncation - 2024-07-11T14:56:29Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/e773b890-e6b2-4406-93a9-71f9a7ab6d73/environment/a9ebbed1-f1ee-4afd-bb14-f603a627ea56/services/general)

 Another comment will be posted when deployments are finished

**Comment by RemiBonnet** [comment]
[Qovery Preview](https://www.qovery.com)
---

Your preview environment failed to be deployed !
Click on the link below to check the deployment logs.
:point_right: [\[PR\] my-env - fix(ui): fix breadcrumb and link truncation - 2024-07-11T14:56:29Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/e773b890-e6b2-4406-93a9-71f9a7ab6d73/environment/a9ebbed1-f1ee-4afd-bb14-f603a627ea56/logs)

**Review by RemiBonnet — CHANGES_REQUESTED** [review]
Thanks !

- I think you need to review all changes for `Link` some things are not correct because you need to add the `ml-1` class. For example with `customize` link

Screenshot 2024-07-16 at 12 25 30



- I noticed another issue, but I think it mostly related to your other PR. To reproduce:
   * Click on the name link inside the list
   * Use go back with navigator

You need two actions "go back" to see previous page, but only once, like when you click on the row. Example on my Loom: https://www.loom.com/share/4eee90acceee4c3f8c5ae68e2c29be2a

**Comment by ctjhoa** [comment]
> Thanks !
> 
>     * I think you need to review all changes for `Link` some things are not correct because you need to add the `ml-1` class. For example with `customize` link
> 
> 
> Screenshot 2024-07-16 at 12 25 30
> 
>     * I noticed another issue, but I think it mostly related to your other PR. To reproduce:
>       
>       * Click on the name link inside the list
>       * Use go back with navigator
> 
> 
> You need two actions "go back" to see previous page, but only once like when you click on the row. Example on my Loom: https://www.loom.com/share/4eee90acceee4c3f8c5ae68e2c29be2a

It should be fixed now

**Review by RemiBonnet — APPROVED** [review]

**Pull request merged**
