### PR TITLE
feat(database): add deployments list and update UI details

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-392
https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-395

- Added Database deployments page
- Fixed logs links for Database, Applications, and Services deployments page
- Updated UI detail for Database and Application
- Warning: I need to update the API Doc because deployments database results are mistyped (I added todo)

Capture d’écran 2022-07-04 à 16 59 20
Capture d’écran 2022-07-04 à 17 01 03

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.  
Click on the link below to follow its deployment and use it.  
:point_right: [[PR] staging - feat(database): add deployments list and update UI details - 2022-07-04T15:02:56Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/ad815483-04a7-4e78-b9f5-9f05ac368e0f/applications)

**Review by WilliamTraoreee — COMMENTED** [review]
Maybe remove the `Commit` column on database deployment page ?

**Review by WilliamTraoreee — APPROVED** [review]
Very good job @RemiBonnet !

**Pull request merged**
