### PR TITLE
feat(deployment-stage-order): add modal

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-655)

- Add modal to ordering stages

Capture d’écran 2023-03-02 à 10 47 26

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(deployment-stage-order): add modal - 2023-03-02T09:47:40Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/62083bf5-3116-4215-b16e-da3e80a166eb/services/general)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z62083bf5-z56186b13-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z62083bf5-zb3c04e14-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
Works great! Code is well divided too, good job!

**Pull request merged**
