### PR TITLE
feat(ui): introduce fontawesome packages

### PR DESCRIPTION
**Pull request by ctjhoa**
# What does this PR do?

https://qovery.atlassian.net/browse/FRT-821

### CODE REVIEW

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] staging - feat(ui): introduce fontawesome packages - 2024-02-21T13:23:56Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/20d5b203-f3f8-4fc5-a44f-3cc8962aa21b/services/general)

 Another comment will be posted when deployments are terminated

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

Your preview environment failed to be deployed !
Click on the link below to check the deployment logs.
:point_right: [\[PR\] staging - feat(ui): introduce fontawesome packages - 2024-02-21T13:23:56Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/20d5b203-f3f8-4fc5-a44f-3cc8962aa21b/logs)

**Comment by ctjhoa** [comment]
https://1187-console-staging.zc531a994.rustrocks.cloud

**Review by RemiBonnet — APPROVED** [review]

**Comment by ctjhoa** [comment]
Superseded by #1203

**Pull request closed without merging**
