### PR TITLE
feat(code-ansi): add utils for logs

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-619)

- Add colors and escape for Logs with ANSI format
- Using [ansi-to-react](https://github.com/nteract/ansi-to-react) library
- Reposition toast files

[All colors](http://localhost:4200/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/b14d2c29-2fbe-42df-9a05-48fa3a66ea88/environment/1601e44f-044c-4d90-b566-9122e7c1485c/application/fef31b63-1d34-4546-9bde-a449df14d559/logs):
Capture d’écran 2023-03-10 à 10 44 29

[Escape example](http://localhost:4200/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/61acd49c-41d9-4354-8e8c-9ae502273a0c/environment/9487452a-1ba5-4f3d-8650-dd7ac6a11cc3/application/1e1455c5-b9e5-4894-a9c2-47bc24bd4a9f/logs):
Capture d’écran 2023-03-10 à 15 49 37

Without: 
Capture d’écran 2023-03-10 à 15 49 57

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(code-ansi): add utils for logs - 2023-03-10T14:52:19Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/8a9c5fae-5d99-4994-97d0-cddce5e35e04/services/general)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z8a9c5fae-zfc172e08-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z8a9c5fae-z592eadf0-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
Very convenient this react library! It works pretty well and the rainbow log wall is wonderful!

**Pull request merged**
