### PR TITLE
feat(navigation-left): add component 

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-351)

- Add the navigation left with react-router logic
- I didn't add an animation when we opened the sub links, it was too much

[Link](http://localhost:4400/?path=/story/navigationleft--primary)

Capture d’écran 2022-07-07 à 17 35 30

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Review by bdebon — CHANGES_REQUESTED** [review]
Remi, I think there is something you should adjust in your vscode config because it always triggers a linter error for me.
For this, as it is in the same library, `Icon` component should be imported as a relative not with a `@`

To put it simply, instead of this
CleanShot 2022-07-11 at 11 42 02@2x

it should be that:
CleanShot 2022-07-11 at 11 43 56@2x

For the rest super work, I like the logic and the way the dev experience is preserved here.
Only one thing to notice, the testing coverage does not look terrible...
CleanShot 2022-07-11 at 11 47 02@2x

**Comment by bdebon** [comment]
Edit: 
It is not very good for `navigation-left` component but it is amazing inside `navigation-left-sub-link`
CleanShot 2022-07-11 at 11 48 09@2x

**Comment by RemiBonnet** [comment]
> For the rest super work, I like the logic and the way the dev experience is preserved here. Only one thing to notice, the testing coverage does not look terrible... CleanShot 2022-07-11 at 11 47 02@2x

Code coverage is good but the problem's from Wallaby, you can see the `navigation-left.spec.tsx`  
Capture d’écran 2022-07-11 à 14 17 43

**Pull request merged**
