### PR TITLE
feat(services): restart button for deployed services

### PR DESCRIPTION
**Pull request by bdebon**
# What does this PR do?

[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-614)

> We should add the “Restart” option in the deployment action menu for any service except managed db , lifecycle job , cronjob
> 
> The option should be available only if the service is deployed. 

CleanShot 2023-01-19 at 16 14 00@2x

---

### Global

- [ ] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [ ] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [ ] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by RemiBonnet** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(services): restart button for deployed services - 2023-01-19T15:14:16Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/1bbcc0c6-c078-4398-b755-f2e61d370a9a/services/general)

 Another comment will be posted when deployments are terminated

**Comment by bdebon** [comment]
I let a lot of TODO to check in the code when api-doc and core will be ready.

**Comment by RemiBonnet** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z1bbcc0c6-z1d13084b-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z1bbcc0c6-z82644828-gtw.za8ad0659.bool.sh)

**Review by RemiBonnet — APPROVED** [review]
LGTM 👍

**Pull request merged**
