### PR TITLE
fix(ui): align dark theme button with designs

### PR DESCRIPTION
**Pull request by ctjhoa**
# What does this PR do?

https://qovery.atlassian.net/browse/FRT-1224

2024-08-02-100842_1912x299_scrot
**with "Logs" button in hover state**

Reference design:

https://www.figma.com/design/L3T54WTTm9rZQwLQHCkcZg/Services-(App-%2F-Database-%2F-Helm)?node-id=22401-78358&t=KxC8L6eixN47nLp7-0

### CODE REVIEW

**Comment by RemiBonnet** [comment]
[Qovery Preview](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview b1cc6d03-1b9e-4536-b5ee-dc186c55218c | [dev](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/b1cc6d03-1b9e-4536-b5ee-dc186c55218c/services/general) |
 /qovery []() preview cc1de7de-94e5-40f8-8e45-bc8986d9dfec | [storybook](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/cc1de7de-94e5-40f8-8e45-bc8986d9dfec/services/general) |
 /qovery []() preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Don’t Sacrifice Readability, you are going to debug it in 6 months

**Review by RemiBonnet — CHANGES_REQUESTED** [review]
Thanks @ctjhoa !

Could you fix the hover state of these buttons as well ? (not sure, it's the good variant)
Screenshot 2024-08-02 at 12 04 10

**Comment by ctjhoa** [comment]
> Thanks @ctjhoa !
> 
> Could you fix the hover state of these buttons as well ? (not sure, it's the good variant) Screenshot 2024-08-02 at 12 04 10

It already fixes both
2024-08-02-142445_1110x400_scrot

**Review by RemiBonnet — APPROVED** [review]

**Pull request merged**
