### PR TITLE
feat(billing): credit card component and CRUD

### PR DESCRIPTION
**Pull request by bdebon**
# What does this PR do?

- Add the InputCreditCard component
- Add the CRUD part of credit part

CleanShot 2023-03-02 at 14 33 02@2x

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(billing): credit card component and CRUD - 2023-03-02T13:34:04Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/2b33a347-cf12-4951-80d3-a1f9dcb15016/services/general)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z2b33a347-zbfb5997d-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z2b33a347-z20b6ef44-gtw.za8ad0659.bool.sh)

**Review by RemiBonnet — COMMENTED** [review]
Well done @bdebon, here my feedback: 

- Bug when I have an error with credit card: https://www.loom.com/share/2b9f3bb52a8443ddb7ec59c4a56955fa

- Be careful, we have files with .js extension should be .ts on the input-credit-card component

- Missing a page name with `useDocumentTitle()`

- I think you can improve the integration 
   - Paragraph is too small should be 12px
   - Background trash button should be transparent (you can inspire by the button on the "Roles & permissions" page with background and hover)
  Capture d’écran 2023-03-02 à 15 58 11
Capture d’écran 2023-03-02 à 15 59 09

**Pull request merged**
