### PR TITLE
feat(organization): danger zone settings

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-494)

Capture d’écran 2022-09-22 à 16 09 23

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(organization): danger zone settings - 2022-09-22T14:09:49Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/88f4676c-f972-4ec7-93cc-0bfe96f049de/applications)

 Another comment will be posted when deployments are terminated

**Review by bdebon — APPROVED** [review]
lgtm! Good that we have a uniformised behavior everywhere. gg

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z88f4676c-z0c27c956-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z88f4676c-z3fdd9d76-gtw.za8ad0659.bool.sh)

**Pull request merged**
