### PR TITLE
Add feedback Breadcrumb

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-367)

- Adding feedback breadcrumb
- Adding truncate on the MenuItem
- Adding truncate on the Header component

Capture d’écran 2022-06-10 à 08 46 20
Capture d’écran 2022-06-10 à 08 46 56

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type-safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by RemiBonnet** [comment]
A preview environment was automatically created via Qovery.  
Click on the link below to follow its deployment and use it.  
:point_right: [[PR] staging - Add feedback Breadcrumb - 2022-06-10T06:47:29Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/b8f2993c-4440-4dff-b999-ca59381bf9ae/applications)

**Comment by evoxmusic** [comment]
@RemiBonnet do we have an "on hover popup" when the name is truncated?

**Comment by RemiBonnet** [comment]
> @RemiBonnet do we have an "on hover popup" when the name is truncated?

Nope @evoxmusic, because I add this with CSS truncate, but I can create a JavaScript helper in some cases to display the full name with a tooltip :)

**Comment by RemiBonnet** [comment]
> @RemiBonnet do we have an "on hover popup" when the name is truncated?

Added,
Capture d’écran 2022-06-10 à 09 51 40

**Review by WilliamTraoreee — APPROVED** [review]
It's way more cleaner with that ! Nice work @RemiBonnet !

**Pull request merged**
