### PR TITLE
fix(job-configure-settings): updated the hint for start event

### PR DESCRIPTION
**Pull request by acarranoqovery**
# What does this PR do?

Just update the wording on the hint for the start event on lifecycle job

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - updated the hint for start event - 2023-02-10T14:35:06Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/09d73467-e169-4527-8379-c4640f81f855/services/general)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z09d73467-zeda5abca-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z09d73467-z37c7c96d-gtw.za8ad0659.bool.sh)

**Review by RemiBonnet — APPROVED** [review]
👍

**Pull request merged**
