### PR TITLE
feat(cluster-advanced-settings): add page

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-499)

- Add advanced settings for Clusters
- For clusters, we can now add "object" for some value

Capture d’écran 2023-01-20 à 16 49 16

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [x] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by RemiBonnet** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(cluster-advanced-settings): add page - 2023-01-19T17:25:40Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/d2201011-3858-45ed-a5f4-a0adafa7f982/services/general)

 Another comment will be posted when deployments are terminated

**Comment by RemiBonnet** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://zd2201011-zd1d35d02-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://zd2201011-z61be00b1-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
Look super Good To Me ! LsGTM
Let's Make Pierre happy!

**Pull request merged**
