### PR TITLE
feat(deployment-stage): create and edit modal

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-655)

- Add actions to delete, update and add stage/group

Capture d’écran 2023-02-27 à 12 52 50

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(deployment-stage): create and edit modal - 2023-02-24T15:57:18Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/b565b029-146b-4fb6-aab6-28256dff079e/services/general)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://zb565b029-z0d1e700a-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://zb565b029-zc08bc6e6-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
Super cool, it works well!
Two suggestions:

In the futur, it could be cool to add a placeholder maybe? Saying something like : add service or delete stage ? wdyt?
CleanShot 2023-02-27 at 13 42 26@2x

And the delete should be in red to be iso with the rest of the console:
CleanShot 2023-02-27 at 13 44 21@2x

That's all Remi! Good job again!

**Pull request merged**
