### PR TITLE
fix(input-select): icon and isMulti

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

- Clean classNames
- Refactoring code (more simple)
- Remove icon translate
- Fix isMulti (selected values on the options list)

Capture d’écran 2022-09-29 à 12 12 58

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix(input-select): icon and isMulti - 2022-09-29T10:13:33Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/ffa66d22-a4ac-4855-9fe8-8bdf15710018/applications)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://zffa66d22-z9944128a-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://zffa66d22-zac26f355-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
Super cool fixes and implementation. Much better that the one I did in a hurry. Gg Rémi!

Two remarks:
- When selected the multi used to keep the options well aligned. Now one select, the option shift on the right (because the check appears). Do we like this? I'm oke-ish with that new behavior. I was also liking the last one. 
https://user-images.githubusercontent.com/6163954/193012567-f90ccf85-a1cf-4495-8eb6-9c9a188bd4cf.mp4

- very cool that you fixed the label up, that's super super cool and it was something I wanted to do for a while. Now it would be nice to apply this fix to: inputText, inputTextarea.
That would be amaaaazing, no more interfaces dancing around every time we open a screen!

Super cool job overall, I'm very happy!

**Pull request merged**
