### PR TITLE
chore(doc): updating links text

### PR DESCRIPTION
**Pull request by acarranoqovery**
# What does this PR do?
- updated text on cluster flow and as well fixed links
- added warning bannerBox on managed db creation flow +  in resources section for both managed db and clusters

> Link to the JIRA ticket

Put description here

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by acarranoqovery** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - Chore/updating links text - 2023-04-20T13:51:56Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/a24070f8-ed29-4b3c-a859-adecbbd5a0b3/services/general)

 Another comment will be posted when deployments are terminated

**Comment by acarranoqovery** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://za24070f8-z4871dd68-gtw.zc531a994.rustrocks.cloud)

**Review by bdebon — APPROVED** [review]
All good! Congrats!

**Comment by acarranoqovery** [comment]
thanks!

**Pull request merged**
