### PR TITLE
feat(shadow-wrapper): adding shadow wrapper component

### PR DESCRIPTION
**Pull request by bdebon**
# What does this PR do?
Adds shadow on desired component when you scroll or when there are things to scroll.

CleanShot 2022-11-15 at 18 09 24@2x

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [ ] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(shadow-wrapper): adding shadow wrapper component - 2022-11-15T17:09:58Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/25be9205-b0c6-4345-9e92-3c1f347a7a58/applications)

 Another comment will be posted when deployments are terminated

**Comment by bdebon** [comment]
I still need to remove the `any` that I have used to type the event and test the wrapper

**Review by RemiBonnet — APPROVED** [review]
Well done, LGTM 👍  !!

**Pull request merged**
