### PR TITLE
feat(organization): structure for settings

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-490)

- Added structure for settings with external links

Capture d’écran 2022-09-14 à 18 00 10

Put screenshot following the template `before` => `after` here

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(organization): structure for settings - 2022-09-13T16:35:26Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/6906296d-414b-4780-9add-272445ffc297/applications)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment have been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z6906296d-z99e79094-gtw.bool.sh)
:point_right: [storybook](https://z6906296d-z980251bf-gtw.bool.sh)

**Review by bdebon — APPROVED** [review]
Superbe! So good to finally see this part of the console!

**Pull request merged**
