### PR TITLE
Environment services table

### PR DESCRIPTION
**Pull request by WilliamTraoreee**
# What does this PR do?

[> Link to the JIRA ticket](https://qovery.atlassian.net/browse/FRT-344)

- Create the environment service table (all services link to an environment)
- Create Tag commit component with the copy commit id feature

image

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by RemiBonnet** [comment]
A preview environment was automatically created via Qovery.  
Click on the link below to follow its deployment and use it.  
:point_right: [[PR] staging - Environment services table - 2022-05-13T12:48:55Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/9fbd2d2e-26ed-44a3-94f1-b78d637941c1/applications)

**Comment by RemiBonnet** [comment]
Please, for the screenshot we need your integration and not the Figma

The commit component is glitched, we need the have the same width for the hover and click, we don't have the same experience with the V2

**Review by RemiBonnet — COMMENTED** [review]
-

**Comment by bdebon** [comment]
When we are loading the data for the first time, the table is empty which is wrong. We should see 2 or 3 lines of placeholders skeletons.
https://user-images.githubusercontent.com/6163954/168549612-0897b645-515f-478e-a02a-8a534b9cf3d0.mp4

The skeletons are all stacked without spaces between them.

**Comment by bdebon** [comment]
On hover there is a slight change of global width which create a very unpleasant shift, probably you should fix the width of both icon to avoid this behavior
https://user-images.githubusercontent.com/6163954/168550202-f1b796af-ad7d-4ec2-94de-d55d08b91044.mp4

**Comment by bdebon** [comment]
Everything is good now! You can merge! Well done!

**Pull request merged**
