### PR TITLE
fix: update wrong min memory usage

### PR DESCRIPTION
**Pull request by deimosfr**
# What does this PR do?

Fix minimum memory limit as it's wrong

### CODE REVIEW

**Comment by acarranoqovery** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix: update wrong min memory usage - 2023-04-25T09:07:37Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/1f2a603d-5968-4b16-94a4-770a530ce572/services/general)

 Another comment will be posted when deployments are terminated

**Comment by acarranoqovery** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z1f2a603d-z453dfe86-gtw.zc531a994.rustrocks.cloud)

**Review by bdebon — APPROVED** [review]
Amazing work Pierre !

**Pull request merged**
