### PR TITLE
fix(database-create): typo fix, snapshots

### PR DESCRIPTION
**Pull request by ishayhil**
# What does this PR do?

A simple typo fix in the database creation configuration modal.

### CODE REVIEW

**Comment by RemiBonnet** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix(database-create): typo fix, stansphots --> snapshots - 2022-11-18T17:40:44Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/d5e75a73-19d1-4adf-8266-f7dc719199f2/applications)

 Another comment will be posted when deployments are terminated

**Comment by RemiBonnet** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://zd5e75a73-za7689405-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://zd5e75a73-z5e56b1ac-gtw.za8ad0659.bool.sh)

**Comment by evoxmusic** [comment]
Thank you @ishayhil for the PR :)

**Comment by RemiBonnet** [comment]
Thank you @ishayhil really appreciate :)

**Pull request merged**
