### PR TITLE
fix(link): add real navigation with react-router

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

- Fix routing for link component

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix(link): add real navigation with react-router - 2023-02-09T14:42:28Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/9893ab78-ea9c-494b-88ea-9ae96e498557/services/general)

 Another comment will be posted when deployments are terminated

**Review by bdebon — APPROVED** [review]
good update!

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z9893ab78-zc7df36b7-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z9893ab78-z3ae3fd4a-gtw.za8ad0659.bool.sh)

**Pull request merged**
