### PR TITLE
fix(wording): fixed wording for information

### PR DESCRIPTION
**Pull request by acarranoqovery**
# What does this PR do?
fixing "information" typos around the repo

> Link to the JIRA ticket

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix: fixed wording for information - 2023-02-13T14:58:22Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/20fdefee-af77-49e8-9fbd-7d1fa17d0909/services/general)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z20fdefee-z80e9e02a-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z20fdefee-z6c1e186d-gtw.za8ad0659.bool.sh)

**Comment by RemiBonnet** [comment]
Thanks @acarranoqovery 💯

**Pull request merged**
