### PR TITLE
Chore/creating store entities interface

### PR DESCRIPTION
**Pull request by bdebon**
# What does this PR do?

[> Link to the JIRA ticket](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23/backlog?selectedIssue=FRT-375)

Add a type to the RootState so we stop using any in a lot of places.
Add the `XXXXEntity` interfaces to factorize custom typing.

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [x] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Review by RemiBonnet — COMMENTED** [review]
Looks good to me !

I have maybe one improvement to avoid duplicating, for each Entity interface:
```
  loadingStatus: 'not loaded' | 'loading' | 'loaded' | 'error' | undefined
  error: string | null | undefined
  joinOrganizationProject: Record<string, string[]>
  ```
  
  Can we extends each entity with a StateInterface or other naming?

**Comment by bdebon** [comment]
> Looks good to me !
> 
> I have maybe one improvement to avoid duplicating, for each Entity interface:
> 
> ```
>   loadingStatus: 'not loaded' | 'loading' | 'loaded' | 'error' | undefined
>   error: string | null | undefined
> ```
> 
> Can we extends each entity with a StateInterface or other naming?

Absolutely! That's a brilliant idea!

**Pull request merged**
