### PR TITLE
fix: uppercaseFirstLetter remove undefined type

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

- Fix util `upperCaseFirstLetter` removing undefined type

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery  preview 28c47145-c8e7-4b9d-8d9e-c65c95b48425 | [staging](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/28c47145-c8e7-4b9d-8d9e-c65c95b48425/services/general) |
| /qovery  preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Help yourself at 2AM by putting some metrics to help observability

**Review by ctjhoa — COMMENTED** [review]
Not sure to really get the reason for those changes but you can define `upperCaseFirstLetter` like this no. It does mostly the same thing no?

```
export const upperCaseFirstLetter = (string = '': string?) =>
  `${string.slice(0, 1).toUpperCase()}${string.toLowerCase().slice(1)}`
```

**Comment by RemiBonnet** [comment]
> Not sure to really get the reason behind those changes but you can define `upperCaseFirstLetter` like this no. It does mostly the same thing no?
> 
> ```js
> export const upperCaseFirstLetter = (string = '': string?) =>
>   `${string.slice(0, 1).toUpperCase()}${string.toLowerCase().slice(1)}`
> ```

Because I am not sure if it makes sense, to return an empty string from this helper, it should always return a string modified no?

**Comment by ctjhoa** [comment]
> > Not sure to really get the reason behind those changes but you can define `upperCaseFirstLetter` like this no. It does mostly the same thing no?
> > ```js
> > export const upperCaseFirstLetter = (string = '': string?) =>
> >   `${string.slice(0, 1).toUpperCase()}${string.toLowerCase().slice(1)}`
> > ```
> 
> Because I am not sure if it makes sense, to return an empty string from this helper, it should always return a string modified no?

As in React `undefined` and empty string is render I

> > Not sure to really get the reason behind those changes but you can define `upperCaseFirstLetter` like this no. It does mostly the same thing no?
> > ```js
> > export const upperCaseFirstLetter = (string = '': string?) =>
> >   `${string.slice(0, 1).toUpperCase()}${string.toLowerCase().slice(1)}`
> > ```
> 
> Because I am not sure if it makes sense, to return an empty string from this helper, it should always return a string modified no?

IMO this is fine because in React `undefined` and empty string are not render anyway. I'm afraid that it will be cumbersome to add string fallback everytime (DX not great)

**Review by ctjhoa — APPROVED** [review]

**Pull request merged**
