### PR TITLE
feat(project): modal to create project

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

- Add a modal to create a project
- Update NavigationLeft component to add left link

Capture d’écran 2022-12-21 à 17 12 43

---

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [x] I have found someone to review this PR and pinged him

### Store

- [ ] This PR introduces new store changes

### NX

- [x] I have run the dep-graph locally and made sure the tree was clean i.e no circular dependencies
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - feat(project): modal to create project - 2022-12-20T16:04:11Z](https://console.qovery.com/platform/organization/141c07c8-0dd9-4623-983b-3fdd61867255/projects/977bd069-20f7-4b24-bd95-28b44174cf43/environments/17931d5d-02f3-44c7-8150-096ebb7e4e79/applications)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z17931d5d-z5fd9ff26-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z17931d5d-ze2a491fd-gtw.za8ad0659.bool.sh)

**Review by bdebon — COMMENTED** [review]
Code review is RAS good!

Testing the UI, gave me this weird cursor issue
https://user-images.githubusercontent.com/6163954/209195560-2685bc3e-f1f5-46bb-acae-25a419d8a3ce.mp4

There is a weird behavior here, if you scroll down in the menu, it scrolls down the whole page and when you click on the element, you have the content of the page not scrolled up
https://user-images.githubusercontent.com/6163954/209195947-ec63e639-4445-4e89-8d7b-98b63a15a141.mp4

The rest is perfect I could create and delete and edit project pretty easily! Nice work! I like this ui/ux, super efficient.

**Pull request merged**
