### PR TITLE
fix(cluster-create): features and resources

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

[> Link to the JIRA ticket
](https://qovery.atlassian.net/jira/software/projects/FRT/boards/23?selectedIssue=FRT-580)

- Updated summary with a real name for instance_type
- Updated features to disabled input select
- Fixed features settings with select

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix(cluster-create): features and resources - 2023-02-08T17:40:07Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/09ad2779-6327-46e7-ab16-5ab0189096fb/services/general)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z09ad2779-zc8043d0c-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z09ad2779-ze45b1e15-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
Working well bg, thanks!

**Pull request merged**
