### PR TITLE
fix(application-buttons-actions): cancel action after deleting

### PR DESCRIPTION
**Pull request by RemiBonnet**
# What does this PR do?

- Cancel deployment after deleting action available
- [Romain's request](https://qovery.slack.com/archives/C02P2JB4SEM/p1677230799228619)

Capture d’écran 2023-02-27 à 16 27 57

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [x] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by evoxmusic** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] staging - fix(application-buttons-actions): cancel action after deleting - 2023-02-27T15:28:43Z](https://new.console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/977bd069-20f7-4b24-bd95-28b44174cf43/environment/48c354ee-b7df-49d8-93a5-4719407f4442/services/general)

 Another comment will be posted when deployments are terminated

**Comment by evoxmusic** [comment]
Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://z48c354ee-zce255c85-gtw.za8ad0659.bool.sh)
:point_right: [storybook](https://z48c354ee-z0c2e7af3-gtw.za8ad0659.bool.sh)

**Review by bdebon — APPROVED** [review]
Except for the fact that `Cancel Deployment` is a weird label to understand that you can Cancel a delete action, this solution is good!

**Comment by RemiBonnet** [comment]
@bdebon fixed !

And I added tests for deleting actions for Environment, Application, and Database.
We have nothing when we delete or cancel deployment for the database should be iso with the application now !

**Review by bdebon — APPROVED** [review]
Amazing, pronounced with the French accent. A-MA-ZINGUE

**Pull request merged**
