### PR TITLE
feat(GCP): add provider support

### PR DESCRIPTION
**Pull request by benjaminch**
- feat(gcp): adding GCP support
- fix: json_credentials field name

# What does this PR do?
Add support got GCP cloud provider in the console.

> Link to the JIRA ticket

GCP will be supported on Qovery, the PR aims to reflect that.

> Screenshot of the feature

---

## PR Checklist

- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] This PR introduces new store changes
- [ ] I have followed the library pattern i.e `feature`, `ui`, `data`, `utils`
- [ ] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] staging - feat: add GCP provider support - 2023-12-15T09:31:14Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/a64f6cc1-4e34-433b-b8fd-5359716fb01b/environment/3e849526-0668-497b-b720-5d8c846512de/services/general)

 Another comment will be posted when deployments are terminated

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [console](https://1038-console-staging.zc531a994.rustrocks.cloud)

**Review by RemiBonnet — APPROVED** [review]

**Review by ctjhoa — APPROVED** [review]

**Pull request merged**
